"""Emit scripts/audio-loudness.json: the measured state of the shipped library.

The manifest is what scripts/validate-audio-loudness.mjs pins against, so it is
generated from the files that are actually in assets/audio, never by hand.
"""
import sys, os, glob, json, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
from dsp import decode, lufs_momentary_max, lufs_integrated, true_peak_db, block_env
from normalise_library import family as lib_family
from design_shots import classify, CLASS_OFFSET, TARGET_M

WIN = 0.20


def channels_of(path):
    r = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'stream=channels',
                        '-of', 'csv=p=0', path], capture_output=True, text=True)
    try:
        return int(r.stdout.strip().splitlines()[0])
    except Exception:
        return 1


def main(src, dst):
    files = {}
    for p in sorted(glob.glob(os.path.join(src, '*.mp3'))):
        stem = os.path.splitext(os.path.basename(p))[0]
        ch = channels_of(p)
        x = decode(p, ch=ch)
        mono = x if ch == 1 else x.mean(axis=0)
        tp = true_peak_db(x) if ch == 1 else max(true_peak_db(x[c]) for c in range(ch))
        e, _ = block_env(mono, 0.01)
        if stem.startswith('shot_'):
            cls, pap, _base = classify(stem)
            fam, extra = 'weapon', {'cls': cls, 'pap': bool(pap)}
        else:
            fam, extra = lib_family(stem), {}
        files[stem] = dict(
            family=fam,
            lufs200=round(lufs_momentary_max(x, win=WIN), 2),
            lufsI=round(lufs_integrated(x), 2),
            dbtp=round(tp, 2),
            peakAt=round(float(np.argmax(e)) * 0.01, 2),
            seconds=round(len(mono) / 48000, 3),
            channels=ch,
            bytes=os.path.getsize(p),
            **extra,
        )
        print('.', end='', flush=True)
    print()
    doc = {
        '_comment': (
            'Generated by the mix-1 mastering pass. Loudness is BS.1770 K-weighted; '
            'lufs200 is the loudest 200 ms window (the metric one-shots are normalised '
            'on), lufsI is ungated integrated loudness, dbtp is 4x-oversampled true peak. '
            'Regenerate with the mastering pipeline - do not hand-edit.'),
        'ceilingDbtp': -1.0,
        'weaponBaseTarget': TARGET_M,
        'weaponClassOffset': CLASS_OFFSET,
        'papOffset': 0.4,
        'files': files,
    }
    with open(dst, 'w') as f:
        json.dump(doc, f, indent=1, sort_keys=False)
        f.write('\n')
    print('wrote', dst, os.path.getsize(dst))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
